<a href="https://colab.research.google.com/github/Nithin0104/CSE305_MachineLearning/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello")

Hello


In [13]:
nums=[0,1,2,3,4]
evensquares=[x ** 2 for x in nums if x%2==0]
print(evensquares)

[0, 4, 16]


In [17]:
file=open("newfile.txt","w")
print (type(file))
a="This will be written to the file."
file.write(a)
file.close()



<class '_io.TextIOWrapper'>


In [19]:
fread=open("newfile.txt")
text=fread.read()
words=text.split()
print( words)
print (sorted(words))


['This', 'will', 'be', 'written', 'to', 'the', 'file.']
['This', 'be', 'file.', 'the', 'to', 'will', 'written']


In [21]:
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [23]:
b = np.array([[1,2,3],[4,5,6]]) 
print( b.shape ) 
print( b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [25]:
a= np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [28]:
b= np.ones((1,2))
print(b)

[[1. 1.]]


In [30]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [32]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [35]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [37]:
import numpy as np
import pandas as pd
df1 = pd.DataFrame({ 'A' : range(1,5),
'B' : pd.Timestamp('20130102'),
'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
df1



A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  2 2013-01-02  1.0  3  train  foo
2  3 2013-01-02  1.0  3   test  foo
3  4 2013-01-02  1.0  3  train  foo